# Generated by Django 3.0 on 2019-12-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDescribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('input_para', models.CharField(max_length=400)),
                ('return_value', models.CharField(max_length=400)),
                ('status_code', models.CharField(max_length=400)),
                ('attention', models.CharField(max_length=400)),
            ],
        ),
    ]
