# Generated by Django 3.0 on 2019-12-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='describe',
            field=models.TextField(default=''),
        ),
    ]
