# Generated by Django 3.0 on 2019-12-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_entry_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='describe',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
