# Generated by Django 3.0 on 2019-12-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20191224_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='describe',
            field=models.TextField(default='', max_length=30),
        ),
    ]
